cargo-features = ["edition"]

[package]
name = "net-parser-rs"
version = "0.1.0"
authors = ["Danny Browning <danny.browning@protectwise.com>"]
edition = "2018"

[dependencies]
arrayref = "~0.3"
nom = "~4.0"
error-chain = "~0.12"
futures-preview = "0.3.0-alpha.2"
log = "~0.4"
pin-utils = "0.1.0-alpha.1"

[dev-dependencies]
env_logger = "*"
hex-slice = "~0.1"